version: '3.9'  # Update to the latest version

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - .:/app
    command: python app.py

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Ensure there is a Dockerfile in the frontend directory
    image: node:16  # Use an official Node.js image
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
